networks:
  download:
    driver: macvlan
    driver_opts:
      parent: enp9s0.4
    ipam:
      config:
        - gateway: 192.168.4.1
          subnet: 192.168.4.0/24
      driver: default

services:
  amd:
    container_name: amd
    hostname: amd
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 1024M
    dns:
      - 192.168.6.6
    entrypoint:
      - /init
    environment:
      ARL_TOKEN: ''
      AUTOSTART: "true"
      BITRATE: '320'
      Concurrency: '1'
      DOWNLOADMODE: wanted
      EMBEDDED_COVER_QUALITY: '80'
      FALLBACKSEARCH: "True"
      FORCECONVERT: "false"
      FORMAT: MP3
      FilePermissions: '666'
      FolderPermissions: '766'
      HOME: /root
      LIST: both
      LidarrAPIkey: ''
      LidarrUrl: https://lidarr.rovacsek.com
      MBRAINZMIRROR: https://musicbrainz.org
      MBRATELIMIT: '1'
      MatchDistance: '10'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      POSTPROCESSTHREADS: '8'
      PGID: 10005
      PUID: 990
      SCRIPTINTERVAL: 6h
      SearchType: both
      TITLESHORT: AMD
      replaygain: "true"
      requirequality: "false"
    image: randomninjaatk/amd:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.142
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/amd:/config:rw
      - /mnt/zfs/downloads:/downloads-amd:rw
    working_dir: /config

  deluge:
    container_name: deluge
    hostname: deluge
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
      - 192.168.6.6
    entrypoint:
      - /init
    environment:
      HOME: /root
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10005'
      PUID: '984'
      PYTHON_EGG_CACHE: /config/plugins/.python-eggs
      TERM: xterm
      TZ: Australia/NSW
      UMASK: '022'
    image: ghcr.io/linuxserver/deluge:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.130
    ports:
      - protocol: tcp
        published: 6881
        target: 6881
      - protocol: udp
        published: 6881
        target: 6881
      - protocol: tcp
        published: 8112
        target: 8112
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/deluge:/config:rw
      - /mnt/zfs/downloads:/downloads:rw

  lidarr:
    container_name: lidarr
    hostname: lidarr
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    entrypoint:
      - /init
    environment:
      PGID: '10002'
      PUID: '990'
      TZ: Australia/NSW
      UMASK: '022'

    image: ghcr.io/linuxserver/lidarr:nightly
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.133
    ports:
      - protocol: tcp
        published: 443
        target: 443
      - protocol: tcp
        published: 8686
        target: 8686
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/lidarr:/config:rw
      - /mnt/zfs/containers/swag/etc/letsencrypt/live/rovacsek.com:/config/rovacsek.com:ro
      - /mnt/zfs/downloads:/downloads:rw
      - /mnt/zfs/downloads:/downloads-amd:rw
      - /mnt/zfs/music:/music:rw

  ombi:
    container_name: ombi
    hostname: ombi
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
      - 192.168.6.6
    entrypoint:
      - /init
    environment:
      HOME: /config
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '65534'
      PUID: '973'
      TERM: xterm
      UMASK: '022'
    image: ghcr.io/linuxserver/ombi:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.134
    ports:
      - protocol: tcp
        published: 3579
        target: 3579
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/ombi:/config:rw

  radarr:
    container_name: radarr
    hostname: radarr
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
      - 192.168.6.6
    entrypoint:
      - /init
    environment:
      HOME: /root
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10002'
      PUID: '986'
      TERM: xterm
      TZ: Australia/NSW
      UMASK: '022'
      XDG_CONFIG_HOME: /config/xdg
    extra_hosts:
      - deluge:192.168.4.130
    image: ghcr.io/linuxserver/radarr:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.132
    ports:
      - protocol: tcp
        published: 7878
        target: 7878
      - protocol: tcp
        published: 8443
        target: 8443
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/radarr:/config:rw
      - /mnt/zfs/containers/swag/etc/letsencrypt/live/rovacsek.com:/config/rovacsek.com:ro
      - /mnt/zfs/downloads:/downloads:rw
      - /mnt/zfs/movies:/movies:rw

  sonarr:
    container_name: sonarr
    hostname: sonarr
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
      - 192.168.6.6
    entrypoint:
      - /init
    environment:
      HOME: /root
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10002'
      PUID: '985'
      SONARR_BRANCH: main
      TERM: xterm
      TZ: Australia/NSW
      UMASK: '022'
      XDG_CONFIG_HOME: /config/xdg
    extra_hosts:
      - deluge:192.168.4.130
    image: ghcr.io/linuxserver/sonarr:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.131
    ports:
      - protocol: tcp
        published: 8989
        target: 8989
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/sonarr:/config:rw
      - /mnt/zfs/downloads:/downloads:rw
      - /mnt/zfs/tv:/tv:rw

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    hostname: prowlarr
    dns:
      - 192.168.6.6
    networks:
      download:
        ipv4_address: 192.168.4.137
    environment:
      PUID: 971
      PGID: 10005
      TZ: Australia/NSW
    volumes:
      - /mnt/zfs/containers/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    dns:
      - 192.168.6.6
    networks:
      download:
        ipv4_address: 192.168.4.138
    environment:
      LOG_LEVEL: info
      TZ: Australia/NSW
    ports:
      - 8191:8191
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    hostname: tdarr-controller
    dns:
      - 192.168.6.6
    image: haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      download:
        ipv4_address: 192.168.4.135
    ports:
      - 8265:8265
      - 8266:8266
    environment:
      TZ: Australia/NSW
      PUID: 974
      PGID: 10002
      UMASK_SET: '002'
      serverIP: 192.168.4.135
      serverPort: 8266
      webUIPort: 8265
    volumes:
      - /mnt/zfs/containers/tdarr/server:/app/server:rw
      - /mnt/zfs/containers/tdarr/configs:/app/configs:rw
      - /mnt/zfs/containers/tdarr/logs:/app/logs:rw
      - /mnt/zfs/movies:/movies:rw
      - /mnt/zfs/tv:/tv:rw
      - /mnt/zfs/music:/music:rw
      - /transcode:/temp:rw
      - /mnt/zfs/test:/test:rw

  tdarr-node-01:
    container_name: tdarr-node-01
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 4096M
    dns:
      - 192.168.6.6
    hostname: tdarr-node-01
    image: haveagitgat/tdarr_node:latest
    ports:
      - 8267:8267
    restart: unless-stopped
    networks:
      download:
        ipv4_address: 192.168.4.136
    runtime: nvidia
    environment:
      TZ: Australia/NSW
      PUID: 974
      PGID: 10002
      UMASK_SET: '002'
      nodeID: tdarr-node-01
      nodeIP: 192.168.4.136
      nodePort: 8267
      serverIP: 192.168.4.135
      serverPort: 8266
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - /mnt/zfs/containers/tdarr/configs:/app/configs:rw
      - /mnt/zfs/containers/tdarr/logs:/app/logs:rw
      - /mnt/zfs/movies:/movies:rw
      - /mnt/zfs/tv:/tv:rw
      - /mnt/zfs/music:/music:rw
      - /transcode:/temp:rw

version: '3'
