networks:
  download:
    driver: macvlan
    driver_opts:
      parent: enp9s0.4
    ipam:
      config:
      - gateway: 192.168.4.1
        subnet: 192.168.4.0/24
      driver: default
services:
  deluge:
    container_name: deluge
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
    - 192.168.6.2
    - 192.168.4.1
    entrypoint:
    - /init
    environment:
      HOME: /root
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10005'
      PUID: '984'
      PYTHON_EGG_CACHE: /config/plugins/.python-eggs
      TERM: xterm
      TZ: Australia/NSW
      UMASK: '022'
    hostname: deluge
    image: ghcr.io/linuxserver/deluge:amd64-latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.130
    ports:
    - protocol: tcp
      published: 6881
      target: 6881
    - protocol: udp
      published: 6881
      target: 6881
    - protocol: tcp
      published: 8112
      target: 8112
    restart: unless-stopped
    volumes:
    - /mnt/zfs/containers/deluge:/config:rw
    - /mnt/zfs/downloads:/downloads:rw
  jackett:
    container_name: jackett
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2048M
    dns:
    - 192.168.6.2
    - 192.168.4.1
    entrypoint:
    - /init
    environment:
      HOME: /root
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10009'
      PUID: '980'
      TERM: xterm
      UMASK: '022'
      XDG_CONFIG_HOME: /config
      XDG_DATA_HOME: /config
    hostname: jackett
    image: ghcr.io/linuxserver/jackett:amd64-latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.129
    ports:
    - protocol: tcp
      published: 9117
      target: 9117
    restart: unless-stopped
    volumes:
    - /mnt/zfs/containers/jackett:/config:rw
    - /mnt/zfs/containers/jackett/blackhole:/downloads:rw
  lidarr:
    container_name: lidarr
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
    - 192.168.6.2
    - 192.168.4.1
    entrypoint:
    - /init
    environment:
      HOME: /root
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10002'
      PUID: '990'
      TERM: xterm
      TZ: Australia/NSW
      UMASK: '022'
      XDG_CONFIG_HOME: /config/xdg
    extra_hosts:
    - deluge:192.168.4.130
    hostname: lidarr
    image: ghcr.io/linuxserver/lidarr:amd64-latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.133
    ports:
    - protocol: tcp
      published: 8443
      target: 8443
    - protocol: tcp
      published: 8686
      target: 8686
    restart: unless-stopped
    volumes:
    - /mnt/zfs/containers/lidarr:/config:rw
    - /mnt/zfs/containers/swag/etc/letsencrypt/live/rovacsek.com:/config/rovacsek.com:rw
    - /mnt/zfs/downloads:/downloads:rw
    - /mnt/zfs/music:/music:rw
  ombi:
    container_name: ombi
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
    - 192.168.6.2
    - 192.168.4.1
    entrypoint:
    - /init
    environment:
      HOME: /config
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '100'
      PUID: '1000'
      TERM: xterm
      UMASK: '022'
    hostname: ombi
    image: ghcr.io/linuxserver/ombi:amd64-development
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.134
    ports:
    - protocol: tcp
      published: 3579
      target: 3579
    restart: unless-stopped
    volumes:
    - /mnt/zfs/containers/ombi:/config:rw
  radarr:
    container_name: radarr
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
    - 192.168.6.2
    - 192.168.4.1
    entrypoint:
    - /init
    environment:
      HOME: /root
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10002'
      PUID: '986'
      TERM: xterm
      TZ: Australia/NSW
      UMASK: '022'
      XDG_CONFIG_HOME: /config/xdg
    extra_hosts:
    - deluge:192.168.4.130
    hostname: radarr
    image: ghcr.io/linuxserver/radarr:amd64-latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.132
    ports:
    - protocol: tcp
      published: 7878
      target: 7878
    - protocol: tcp
      published: 8443
      target: 8443
    restart: unless-stopped
    volumes:
    - /mnt/zfs/containers/radarr:/config:rw
    - /mnt/zfs/containers/swag/etc/letsencrypt/live/rovacsek.com:/config/rovacsek.com:rw
    - /mnt/zfs/downloads:/downloads:rw
    - /mnt/zfs/movies:/movies:rw
  sonarr:
    container_name: sonarr
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2048M
    dns:
    - 192.168.6.2
    - 192.168.4.1
    entrypoint:
    - /init
    environment:
      HOME: /root
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10002'
      PUID: '985'
      SONARR_BRANCH: main
      TERM: xterm
      TZ: Australia/NSW
      UMASK: '022'
      XDG_CONFIG_HOME: /config/xdg
    extra_hosts:
    - deluge:192.168.4.130
    hostname: sonarr
    image: ghcr.io/linuxserver/sonarr:amd64-latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      download:
        ipv4_address: 192.168.4.131
    ports:
    - protocol: tcp
      published: 8989
      target: 8989
    restart: unless-stopped
    volumes:
    - /mnt/zfs/containers/sonarr:/config:rw
    - /mnt/zfs/downloads:/downloads:rw
    - /mnt/zfs/tv:/tv:rw
version: '3'

