networks:
  dns:
    driver: macvlan
    driver_opts:
      parent: enp9s0.6
    ipam:
      config:
      - gateway: 192.168.6.1
        subnet: 192.168.6.0/24
      driver: default
  home_assistant:
    driver: macvlan
    driver_opts:
      parent: enp9s0.12
    ipam:
      config:
      - gateway: 192.168.12.1
        subnet: 192.168.12.0/24
      driver: default
services:
  home-assistant:
    container_name: home-assistant
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2048M
    dns:
    - 192.168.6.2
    - 192.168.12.1
    entrypoint:
    - /init
    environment:
      LANG: C.UTF-8
      PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      S6_BEHAVIOUR_IF_STAGE2_FAILS: '2'
      S6_CMD_WAIT_FOR_SERVICES: '1'
      S6_SERVICES_GRACETIME: '220000'
      WHEELS_LINKS: https://wheels.home-assistant.io/alpine-3.13/amd64/
    hostname: homeassistant
    image: homeassistant/home-assistant:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      home_assistant:
        ipv4_address: 192.168.12.2
    ports:
    - protocol: tcp
      published: 8123
      target: 8123
    restart: unless-stopped
    volumes:
    - /mnt/zfs/home_assistant:/config:rw
    working_dir: /config
  pihole:
    container_name: pihole
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2048M
    dns:
    - 1.1.1.1
    - 8.8.8.8
    entrypoint:
    - /s6-init
    environment:
      DNS1: 127.1.1.1#5153
      DNS2: 127.2.2.2#5253
      DNSMASQ_LISTENING: all
      DNSMASQ_USER: root
      FTL_CMD: no-daemon
      INTERFACE: enp9s0
      IPv6: "false"
      PATH: /opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PHP_ENV_CONFIG: /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
      PHP_ERROR_LOG: /var/log/lighttpd/error.log
      PIHOLE_ARCH: amd64
      PIHOLE_INSTALL: /etc/.pihole/automated install/basic-install.sh
      S6OVERLAY_RELEASE: https://github.com/just-containers/s6-overlay/releases/download/v2.1.0.2/s6-overlay-amd64.tar.gz
      S6_BEHAVIOUR_IF_STAGE2_FAILS: '2'
      S6_KEEP_ENV: '1'
      S6_LOGGING: '0'
      ServerIP: 192.168.6.2
      TZ: Australia/NSW
      VERSION: v5.3.1
      WEBPASSWORD: ''
    hostname: pihole
    image: testdasi/pihole-dot-doh:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      dns:
        ipv4_address: 192.168.6.2
    ports:
    - protocol: tcp
      published: 443
      target: 443
    - protocol: tcp
      published: 53
      target: 53
    - protocol: udp
      published: 53
      target: 53
    - protocol: udp
      published: 67
      target: 67
    - protocol: tcp
      published: 80
      target: 80
    restart: unless-stopped
    volumes:
    - /mnt/zfs/containers/pihole/pihole:/etc/pihole:rw
    - /mnt/zfs/containers/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
    - /mnt/zfs/containers/pihole/config:/config:rw
version: '3'

