networks:
  lan:
    external: true
    name: lan
services:
  duplicati:
    container_name: duplicati
    image: ghcr.io/linuxserver/duplicati
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 4096M
    dns:
      - 192.168.6.6
    networks:
      lan:
        ipv4_address: 192.168.1.223
    environment:
      - PUID=983
      - PGID=10014
      - TZ=Australia/NSW
    volumes:
      - /mnt/zfs/containers/duplicati:/config
      - /mnt/zfs/backup:/backups
      - /backup:/backup
      - /mnt/zfs:/source
    ports:
      - 8200:8200
    restart: unless-stopped

version: '3'
