networks:
  reverse_proxy:
    external: true
    name: reverse_proxy
services:
  swag:
    container_name: swag
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 4096M
    dns:
      - 192.168.6.4
      - 192.168.6.2
    entrypoint:
      - /init
    environment:
      AWS_CONFIG_FILE: /config/dns-conf/route53.ini
      DHLEVEL: '4096'
      EMAIL: letsencrypt@rovacsek.com
      HOME: /root
      ONLY_SUBDOMAINS: "false"
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PGID: '10015'
      PUID: '976'
      S6_BEHAVIOUR_IF_STAGE2_FAILS: '2'
      STAGING: "false"
      SUBDOMAINS: pfsense,nextcloud,authelia,jellyfin,ombi,radarr,sonarr,lidarr,duplicati,pihole,portainer,homeassistant,tdarr,prowlarr
      TERM: xterm
      UMASK: '002'
      URL: rovacsek.com
      VALIDATION: http
    hostname: swag
    image: ghcr.io/linuxserver/swag:amd64-latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      reverse_proxy:
        ipv4_address: 192.168.5.3
    ports:
      - protocol: tcp
        published: 443
        target: 443
      - protocol: tcp
        published: 80
        target: 80
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/swag:/config:rw
version: '3'
