networks:
  lan:
    external: true
    name: lan

services:
  stable-diffusion:
    container_name: stable-diffusion
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 12G
    dns:
      - 192.168.6.4
      - 192.168.6.2
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - WEBUI_SCRIPT=webui_streamlit.py
      - VALIDATE_MODELS=false
    hostname: stable-diffusion
    image: hlky/sd-webui:runpod
    runtime: nvidia
    networks:
      lan:
        ipv4_address: 192.168.1.226
    ports:
      - 8501:8501/tcp
      - 8501:8501/udp
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/stable-diffusion:/sd/outputs
version: "3"
