networks:
  dns:
    driver: macvlan
    driver_opts:
      parent: enp9s0.6
    ipam:
      config:
        - gateway: 192.168.6.1
          subnet: 192.168.6.0/24
      driver: default
services:
  pihole:
    container_name: pihole
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2048M

    environment:
      PIHOLE_DNS_: 192.168.6.3#8053
      TZ: "Australia/Sydney"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      DHCP_ACTIVE: "false"
      DNSMASQ_LISTENING: "all"
      DNSMASQ_USER: "pihole"
      IPv6: "false"
      WEBPASSWORD: "password"
      WEBTHEME: "default-dark"
      CUSTOM_CACHE_SIZE: "10000"
      FTL_CMD: "no-daemon -- --dns-forward-max 500"
      FTLCONF_RESOLVE_IPV6: "no"
      FTLCONF_SOCKET_LISTENING: "all"
      FTLCONF_NAMES_FROM_NETDB: "true"
      FTLCONF_REPLY_WHEN_BUSY: "DROP"
      FTLCONF_SHOW_DNSSEC: "true"
      FTLCONF_RATE_LIMIT: "0/0"
      FTLCONF_EDNS0_ECS: "true"
    hostname: pihole
    image: pihole/pihole:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      dns:
        ipv4_address: 192.168.6.2
    ports:
      - protocol: tcp
        published: 443
        target: 443
      - protocol: tcp
        published: 53
        target: 53
      - protocol: udp
        published: 53
        target: 53
      - protocol: udp
        published: 67
        target: 67
      - protocol: tcp
        published: 80
        target: 80
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/pihole/pihole:/etc/pihole:rw
      - /mnt/zfs/containers/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /mnt/zfs/containers/pihole/config:/config:rw

  stubby:
    container_name: stubby
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 1024M
    networks:
      dns:
        ipv4_address: 192.168.6.3
    hostname: stubby
    image: "mvance/stubby:latest"
    ports:
      - protocol: udp
        published: 8053
        target: 8053
    restart: unless-stopped
    volumes:
      - /mnt/zfs/containers/stubby:/opt/stubby/etc/stubby:rw

version: '3'
