networks:
  dns:
    driver: macvlan
    driver_opts:
      parent: enp9s0.6
    ipam:
      config:
      - gateway: 192.168.6.1
        subnet: 192.168.6.0/24
      driver: default
services:
  pihole:
    container_name: pihole
    cap_add:
    - NET_BIND_SERVICE
    - NET_RAW
    - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2048M
    dns:
    - 127.0.0.1
    - 1.1.1.1
    environment:
      PIHOLE_DNS_: 8.8.8.8;8.8.4.4;9.9.9.9;1.1.1.1;1.0.0.1
      DNSSEC: "true"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      DHCP_ACTIVE: "false"
      DNSMASQ_LISTENING: all
      ServerIP: 192.168.6.2
      TZ: Australia/NSW
      WEBPASSWORD: ''
    hostname: pihole
    image: pihole/pihole:latest
    ipc: private
    logging:
      driver: journald
      options: {}
    networks:
      dns:
        ipv4_address: 192.168.6.2
    ports:
    - protocol: tcp
      published: 443
      target: 443
    - protocol: tcp
      published: 53
      target: 53
    - protocol: udp
      published: 53
      target: 53
    - protocol: udp
      published: 67
      target: 67
    - protocol: tcp
      published: 80
      target: 80
    restart: unless-stopped
    volumes:
    - /mnt/zfs/containers/pihole/pihole:/etc/pihole:rw
    - /mnt/zfs/containers/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
    - /mnt/zfs/containers/pihole/config:/config:rw

version: '3'